GemLevels = [
  'Raw',
  'Uncut',
  'Rough',
  'Flawed',
  'Imperfect',
  'Polished',
  'Faceted',
  'Precious',
  'Flawless',
  'Perfect'
]

StatPrefixMap = {
  'Strength': 'Fiery',
  'Constitution': 'Earthen',
  'Dexterity': 'Vapor',
  'Quickness': 'Airy',
  'Intelligence': 'Dusty',
  'Piety': 'Watery',
  'Charisma': 'Icy',
  'Empathy': 'Heated',
  'Power': 'Mystical',
  'Hits': 'Blood'
}

ResistPrefixMap = {
  'Body': 'Dusty',
  'Cold': 'Icy',
  'Heat': 'Heated',
  'Energy': 'Light',
  'Matter': 'Earthen',
  'Spirit': 'Vapor',
  'Crush': 'Fiery',
  'Thrust': 'Airy',
  'Slash': 'Watery'
};

SkillGems = [
  { realm: 'Albion', name: 'All Magic Skills', gems: ['Mystic', 'Fervor Sigil'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] },
  { realm: 'Albion', name: 'All Melee Weapon Skills', gems: ['Finesse', 'War Sigil'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] },
  { realm: 'Albion', name: 'Archery', gems: ['Airy', 'War Sigil'], classes: [12] },
  { realm: 'Albion', name: 'Aura Manipulation', gems: ['Radiant', 'Fervor Sigil'], classes: [6] },
  { realm: 'Albion', name: 'Body Magic', gems: ['Heated', 'Evocation Sigil'], classes: [1, 13] },
  { realm: 'Albion', name: 'Chants', gems: ['Earthen', 'Fervor Sigil'], classes: [10] },
  { realm: 'Albion', name: 'Cold Magic', gems: ['Icy', 'Evocation Sigil'], classes: [14, 15] },
  { realm: 'Albion', name: 'Critical Strike', gems: ['Heated', 'Battle Jewel'], classes: [5] },
  { realm: 'Albion', name: 'Crossbow', gems: ['Vapor', 'War Sigil'], classes: [0] },
  { realm: 'Albion', name: 'Crush', gems: ['Fiery', 'War Sigil'], classes: [0, 7, 10] },
  { realm: 'Albion', name: 'Death Servant', gems: ['Ashen', 'Fervor Sigil'], classes: [9] },
  { realm: 'Albion', name: 'Deathsight', gems: ['Vacuous', 'Fervor Sigil'], classes: [9] },
  { realm: 'Albion', name: 'Dual Wield', gems: ['Icy', 'War Sigil'], classes: [5, 7] },
  { realm: 'Albion', name: 'Earth Magic', gems: ['Earthen', 'Evocation Sigil'], classes: [14, 15] },
  { realm: 'Albion', name: 'Enhancement', gems: ['Airy', 'Fervor Sigil'], classes: [2, 3, 4] },
  { realm: 'Albion', name: 'Envenom', gems: ['Dusty', 'Battle Jewel'], classes: [5] },
  { realm: 'Albion', name: 'Flexible', gems: ['Molten Magma', 'War Sigil'], classes: [4, 11] },
  { realm: 'Albion', name: 'Fire Magic', gems: ['Fiery', 'Evocation Sigil'], classes: [15] },
  { realm: 'Albion', name: 'Fist Wraps', gems: ['Glacial', 'War Sigil'], classes: [6] },
  { realm: 'Albion', name: 'Instruments', gems: ['Vapor', 'Fervor Sigil'], classes: [8] },
  { realm: 'Albion', name: 'Magnetism', gems: ['Magnetic', 'Fervor Sigil'], classes: [6] },
  { realm: 'Albion', name: 'Matter Magic', gems: ['Dusty', 'Evocation Sigil'], classes: [1, 13] },
  { realm: 'Albion', name: 'Mauler Staff', gems: ['Cinder', 'War Sigil'], classes: [6] },
  { realm: 'Albion', name: 'Mind Magic', gems: ['Watery', 'Evocation Sigil'], classes: [13] },
  { realm: 'Albion', name: 'Painworking', gems: ['Salt Crusted', 'Fervor Sigil'], classes: [9] },
  { realm: 'Albion', name: 'Parry', gems: ['Vapor', 'Battle Jewel'], classes: [0, 7, 10, 11] },
  { realm: 'Albion', name: 'Polearm', gems: ['Earthen', 'War Sigil'], classes: [0] },
  { realm: 'Albion', name: 'Power Strikes', gems: ['Clout', 'Fervor Sigil'], classes: [6] },
  { realm: 'Albion', name: 'Rejuvenation', gems: ['Watery', 'Fervor Sigil'], classes: [2, 3, 4] },
  { realm: 'Albion', name: 'Shield', gems: ['Fiery', 'Battle Jewel'], classes: [0, 4, 7, 10, 11, 12] },
  { realm: 'Albion', name: 'Slash', gems: ['Watery', 'War Sigil'], classes: [0, 5, 7, 8, 10, 11, 12] },
  { realm: 'Albion', name: 'Smite', gems: ['Fiery', 'Fervor Sigil'], classes: [2] },
  { realm: 'Albion', name: 'Soulrending', gems: ['Steaming', 'Fervor Sigil'], classes: [11] },
  { realm: 'Albion', name: 'Spirit Magic', gems: ['Vapor', 'Evocation Sigil'], classes: [1] },
  { realm: 'Albion', name: 'Staff', gems: ['Earthen', 'Battle Jewel'], classes: [3, 6] },
  { realm: 'Albion', name: 'Stealth', gems: ['Airy', 'Battle Jewel'], classes: [5, 8, 12] },
  { realm: 'Albion', name: 'Thrust', gems: ['Dusty', 'War Sigil'], classes: [0, 5, 7, 8, 11, 12] },
  { realm: 'Albion', name: 'Two Handed', gems: ['Heated', 'War Sigil'], classes: [0, 10] },
  { realm: 'Albion', name: 'Wind Magic', gems: ['Airy', 'Evocation Sigil'], classes: [14] },

  { realm:'Hibernia', name: 'All Magic Skills', gems: ['Mystic', 'Nature Spell Stone'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] },
  { realm:'Hibernia', name: 'All Melee Weapon Skills', gems: ['Finesse', 'War Spell Stone'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] },
  { realm:'Hibernia', name: 'Arboreal Path', gems: ['Steaming', 'Nature Spell Stone'], classes: [0, 13] },
  { realm:'Hibernia', name: 'Archery', gems: ['Airy', 'War Spell Stone'], classes: [12] },
  { realm:'Hibernia', name: 'Aura Manipulation', gems: ['Radiant', 'Nature Spell Stone'], classes: [9] },
  { realm:'Hibernia', name: 'Blades', gems: ['Watery', 'War Spell Stone'], classes: [2, 3, 4, 8, 11, 12, 15] },
  { realm:'Hibernia', name: 'Blunt', gems: ['Fiery', 'War Spell Stone'], classes: [2, 3, 8] },
  { realm:'Hibernia', name: 'Celtic Dual', gems: ['Icy', 'War Spell Stone'], classes: [3, 11,12] },
  { realm:'Hibernia', name: 'Celtic Spear', gems: ['Earthen', 'War Spell Stone'], classes: [8] },
  { realm:'Hibernia', name: 'Creeping Path', gems: ['Oozing', 'Nature Spell Stone'], classes: [0] },
  { realm:'Hibernia', name: 'Critical Strike', gems: ['Heated', 'Battle Jewel'], classes: [11] },
  { realm:'Hibernia', name: 'Dementia', gems: ['Aberrant', 'Arcane Spell Stone'], classes: [14] },
  { realm:'Hibernia', name: 'Enchantments', gems: ['Vapor', 'Arcane Spell Stone'], classes: [7] },
  { realm:'Hibernia', name: 'Envenom', gems: ['Dusty', 'Battle Jewel'], classes: [11] },
  { realm:'Hibernia', name: 'Ethereal Shriek', gems: ['Ethereal', 'Arcane Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Fist Wraps', gems: ['Glacial', 'War Spell Stone'], classes: [9] },
  { realm:'Hibernia', name: 'Large Weaponry', gems: ['Heated', 'War Spell Stone'], classes: [4, 8] },
  { realm:'Hibernia', name: 'Light', gems: ['Fiery', 'Arcane Spell Stone'], classes: [6, 7, 10] },
  { realm:'Hibernia', name: 'Magnetism', gems: ['Magnetic', 'Nature Spell Stone'], classes: [9] },
  { realm:'Hibernia', name: 'Mana', gems: ['Watery', 'Arcane Spell Stone'], classes: [6, 7, 10] },
  { realm:'Hibernia', name: 'Mauler Staff', gems: ['Cinder', 'War Spell Stone'], classes: [9] },
  { realm:'Hibernia', name: 'Mentalism', gems: ['Earthen', 'Arcane Spell Stone'], classes: [10] },
  { realm:'Hibernia', name: 'Music', gems: ['Airy', 'Nature Spell Stone'], classes: [2] },
  { realm:'Hibernia', name: 'Nature', gems: ['Earthen', 'Nature Spell Stone'], classes: [5, 15] },
  { realm:'Hibernia', name: 'Nurture', gems: ['Fiery', 'Nature Spell Stone'], classes: [2, 5, 15] },
  { realm:'Hibernia', name: 'Parry', gems: ['Vapor', 'Battle Jewel'], classes: [3, 4, 8, 13, 15] },
  { realm:'Hibernia', name: 'Phantasmal Wail', gems: ['Phantasmal', 'Arcane Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Piercing', gems: ['Dusty', 'War Spell Stone'], classes: [3, 4, 8, 11, 12, 14] },
  { realm:'Hibernia', name: 'Power Strikes', gems: ['Clout', 'Nature Spell Stone'], classes: [9] },
  { realm:'Hibernia', name: 'Regrowth', gems: ['Watery', 'Nature Spell Stone'], classes: [2, 5, 15] },
  { realm:'Hibernia', name: 'Scythe', gems: ['Light', 'War Spell Stone'], classes: [13] },
  { realm:'Hibernia', name: 'Shadow Mastery', gems: ['Shadowy', 'Arcane Spell Stone'], classes: [14] },
  { realm:'Hibernia', name: 'Shield', gems: ['Fiery', 'Battle Jewel'], classes: [3, 4, 8, 15] },
  { realm:'Hibernia', name: 'Spectral Guard', gems: ['Spectral', 'Arcane Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Staff', gems: ['Earthen', 'Battle Jewel'], classes: [9] },
  { realm:'Hibernia', name: 'Stealth', gems: ['Airy', 'Battle Jewel'], classes: [11, 12] },
  { realm:'Hibernia', name: 'Valor', gems: ['Airy', 'Arcane Spell Stone'], classes: [4] },
  { realm:'Hibernia', name: 'Vampiiric Embrace', gems: ['Embracing', 'Arcane Spell Stone'], classes: [14] },
  { realm:'Hibernia', name: 'Verdant Path', gems: ['Mineral Encrusted', 'Nature Spell Stone'], classes: [0] },
  { realm:'Hibernia', name: 'Void', gems: ['Icy', 'Arcane Spell Stone'], classes: [6] },

  { realm:'Midgard', name: 'All Magic Skills', gems: ['Mystic', 'Primal Rune'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] },
  { realm:'Midgard', name: 'All Melee Weapon Skills', gems: ['Finesse', 'War Rune'], classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] },
  { realm:'Midgard', name: 'Archery', gems: ['Airy', 'War Rune'], classes: [3] },
  { realm:'Midgard', name: 'Augmentation', gems: ['Airy', 'Chaos Rune'], classes: [2, 8] },
  { realm:'Midgard', name: 'Aura Manipulation', gems: ['Radiant', 'Primal Rune'], classes: [4] },
  { realm:'Midgard', name: 'Axe', gems: ['Earthen', 'War Rune'], classes: [0, 6, 7, 11, 14] },
  { realm:'Midgard', name: 'Battlesongs', gems: ['Airy', 'Primal Rune'], classes: [9] },
  { realm:'Midgard', name: 'Beastcraft', gems: ['Earthen', 'Primal Rune'], classes: [3] },
  { realm:'Midgard', name: 'Bone Army', gems: ['Ashen', 'Primal Rune'], classes: [1] },
  { realm:'Midgard', name: 'Cave Magic', gems: ['Fiery', 'Chaos Rune'], classes: [8] },
  { realm:'Midgard', name: 'Critical Strike', gems: ['Heated', 'Battle Jewel'], classes: [7] },
  { realm:'Midgard', name: 'Cursing', gems: ['Blighted', 'Primal Rune'], classes: [13] },
  { realm:'Midgard', name: 'Darkness', gems: ['Icy', 'Chaos Rune'], classes: [10] },
  { realm:'Midgard', name: 'Envenom', gems: ['Dusty', 'Battle Jewel'], classes: [7] },
  { realm:'Midgard', name: 'Fist Wraps', gems: ['Glacial', 'War Rune'], classes: [4] },
  { realm:'Midgard', name: 'Hammer', gems: ['Fiery', 'War Rune'], classes: [0, 9, 11, 14] },
  { realm:'Midgard', name: 'Hand To Hand', gems: ['Lightning Charged', 'War Rune'], classes: [6] },
  { realm:'Midgard', name: 'Hexing', gems: ['Unholy', 'Primal Rune'], classes: [13] },
  { realm:'Midgard', name: 'Left Axe', gems: ['Icy', 'War Rune'], classes: [0, 7] },
  { realm:'Midgard', name: 'Magnetism', gems: ['Magnetic', 'Primal Rune'], classes: [4] },
  { realm:'Midgard', name: 'Mauler Staff', gems: ['Cinder', 'War Rune'], classes: [4] },
  { realm:'Midgard', name: 'Mending', gems: ['Watery', 'Chaos Rune'], classes: [2, 9] },
  { realm:'Midgard', name: 'Odin\'s Will', gems: ['Valiant', 'Primal Rune'], classes: [12] },
  { realm:'Midgard', name: 'Parry', gems: ['Vapor', 'Battle Jewel'], classes: [0, 6, 9, 11, 12, 14] },
  { realm:'Midgard', name: 'Power Strikes', gems: ['Clout', 'Primal Rune'], classes: [4] },
  { realm:'Midgard', name: 'Runecarving', gems: ['Heated', 'Chaos Rune'], classes: [5] },
  { realm:'Midgard', name: 'Shield', gems: ['Fiery', 'Battle Jewel'], classes: [11, 12, 14] },
  { realm:'Midgard', name: 'Spear', gems: ['Heated', 'War Rune'], classes: [3, 12] },
  { realm:'Midgard', name: 'Staff', gems: ['Earthen', 'Battle Jewel'], classes: [4] },
  { realm:'Midgard', name: 'Stealth', gems: ['Airy', 'Battle Jewel'], classes: [3, 7] },
  { realm:'Midgard', name: 'Stormcalling', gems: ['Fiery', 'Primal Rune'], classes: [11] },
  { realm:'Midgard', name: 'Summoning', gems: ['Vapor', 'Chaos Rune'], classes: [10] },
  { realm:'Midgard', name: 'Suppression', gems: ['Dusty', 'Chaos Rune'], classes: [5] },
  { realm:'Midgard', name: 'Sword', gems: ['Watery', 'War Rune'], classes: [0, 3, 6, 7, 9, 12, 14] },
  { realm:'Midgard', name: 'Thrown Weapons', gems: ['Vapor', 'War Rune'], classes: [0, 7, 14] }
],

FocusGems = [
  { realm:'Albion', name: 'All Spell Lines', gems: ['Brilliant', 'Sigil'], classes: [1, 9, 13, 14, 15] },
  { realm:'Albion', name: 'Body Magic', gems: ['Heat', 'Sigil'], classes: [1, 13] },
  { realm:'Albion', name: 'Cold Magic', gems: ['Ice', 'Sigil'], classes: [14, 15] },
  { realm:'Albion', name: 'Death Servant', gems: ['Ashen', 'Sigil'], classes: [9] },
  { realm:'Albion', name: 'Deathsight', gems: ['Vacuous', 'Sigil'], classes: [9] },
  { realm:'Albion', name: 'Earth Magic', gems: ['Earth', 'Sigil'], classes: [14, 15] },
  { realm:'Albion', name: 'Fire Magic', gems: ['Fire', 'Sigil'], classes: [15] },
  { realm:'Albion', name: 'Matter Magic', gems: ['Dust', 'Sigil'], classes: [1, 13] },
  { realm:'Albion', name: 'Mind Magic', gems: ['Water', 'Sigil'], classes: [13] },
  { realm:'Albion', name: 'Painworking', gems: ['Salt Crusted', 'Sigil'], classes: [9] },
  { realm:'Albion', name: 'Spirit Magic', gems: ['Vapor', 'Sigil'], classes: [1] },
  { realm:'Albion', name: 'Wind Magic', gems: ['Air', 'Sigil'], classes: [14] },

  { realm:'Hibernia', name: 'All Spell Lines', gems: ['Brilliant', 'Spell Stone'], classes: [0, 1, 6, 7, 10] },
  { realm:'Hibernia', name: 'Arboreal Path', gems: ['Steaming', 'Spell Stone'], classes: [0] },
  { realm:'Hibernia', name: 'Creeping Path', gems: ['Oozing', 'Spell Stone'], classes: [0] },
  { realm:'Hibernia', name: 'Enchantments', gems: ['Vapor', 'Spell Stone'], classes: [7] },
  { realm:'Hibernia', name: 'Ethereal Shriek', gems: ['Ethereal', 'Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Light', gems: ['Fire', 'Spell Stone'], classes: [6, 7, 10] },
  { realm:'Hibernia', name: 'Mana', gems: ['Water', 'Spell Stone'], classes: [6, 7, 10] },
  { realm:'Hibernia', name: 'Mentalism', gems: ['Earth', 'Spell Stone'], classes: [10] },
  { realm:'Hibernia', name: 'Phantasmal Wail', gems: ['Phantasmal', 'Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Spectral Guard', gems: ['Spectral', 'Spell Stone'], classes: [1] },
  { realm:'Hibernia', name: 'Verdant Path', gems: ['Mineral Encrusted', 'Spell Stone'], classes: [0] },
  { realm:'Hibernia', name: 'Void', gems: ['Ice', 'Spell Stone'], classes: [6] },

  { realm:'Midgard', name: 'All Spell Lines', gems: ['Brilliant', 'Rune'], classes: [1, 5, 10, 13] },
  { realm:'Midgard', name: 'Bone Army', gems: ['Ashen', 'Rune'], classes: [1] },
  { realm:'Midgard', name: 'Cursing', gems: ['Blighted', 'Rune'], classes: [13] },
  { realm:'Midgard', name: 'Darkness', gems: ['Ice', 'Rune'], classes: [1, 5, 10] },
  { realm:'Midgard', name: 'Runecarving', gems: ['Heat', 'Rune'], classes: [5] },
  { realm:'Midgard', name: 'Summoning', gems: ['Vapor', 'Rune'], classes: [10] },
  { realm:'Midgard', name: 'Suppression', gems: ['Dust', 'Rune'], classes: [1, 5, 10] }
];

Gems = [
  'Lo',
  'Um',
  'On',
  'Ee',
  'Pal',
  'Mon',
  'Ros',
  'Zo',
  'Kath',
  'Ra'
]

Dusts = [
  { name: 'Essence Jewel',        mat: 'Essence of Life' },
  { name: 'Shielding Jewel',      mat: 'Ground Draconic Scales' },
  { name: 'Spell Stone',          mat: 'Ground Draconic Scales' },
  { name: 'Sigil',                mat: 'Ground Draconic Scales' },
  { name: 'Rune',                 mat: 'Ground Draconic Scales' },
  { name: 'Chaos Rune',           mat: 'Soot From Niflheim' },
  { name: 'Battle Jewel',         mat: 'Bloodied Battlefield Dirt' },
  { name: 'War Rune',             mat: 'Ground Giant Bone' },
  { name: 'Primal Rune',          mat: 'Ground Vendo Bone' },
  { name: 'Evocation Sigil',      mat: 'Ground Cave Crystal' },
  { name: 'Fervor Sigil',         mat: 'Ground Blessed Undead Bone' },
  { name: 'War Sigil',            mat: 'Ground Caer Stone' },
  { name: 'Nature Spell Stone',   mat: 'Fairy Dust' },
  { name: 'War Spell Stone',      mat: 'Unseelie Dust' },
  { name: 'Arcane Spell Stone',   mat: 'Other Worldly Dust' }
];

DustsOrder = [
  'Bloodied Battlefield Dirt',
  'Essence of Life',
  'Fairy Dust',
  'Ground Blessed Undead Bone',
  'Ground Caer Stone',
  'Ground Cave Crystal',
  'Ground Draconic Scales',
  'Ground Giant Bone',
  'Ground Vendo Bone',
  'Other Worldly Dust',
  'Soot From Niflheim',
  'Unseelie Dust'
];

Liquids = [
  { name: 'Fiery',              mat: ['Draconic Fire'] },
  { name: 'Earthen',            mat: ['Treant Blood'] },
  { name: 'Vapor',              mat: ['Swamp Fog'] },
  { name: 'Airy',               mat: ['Air Elemental Essence'] },
  { name: 'Heated',             mat: ['Heat From an Unearthly Pyre'] },
  { name: 'Icy',                mat: ['Frost From a Wasteland'] },
  { name: 'Watery',             mat: ['Leviathan Blood'] },
  { name: 'Dusty',              mat: ['Undead Ash and Holy Water'] },
  { name: 'Fire',               mat: ['Draconic Fire'] },
  { name: 'Earth',              mat: ['Treant Blood'] },
  { name: 'Vapor',              mat: ['Swamp Fog'] },
  { name: 'Air',                mat: ['Air Elemental Essence'] },
  { name: 'Heat',               mat: ['Heat From an Unearthly Pyre'] },
  { name: 'Ice',                mat: ['Frost From a Wasteland'] },
  { name: 'Water',              mat: ['Leviathan Blood'] },
  { name: 'Dust',               mat: ['Undead Ash and Holy Water'] },
  { name: 'Ashen',              mat: ['Undead Ash and Holy Water'] },
  { name: 'Vacuous',            mat: ['Swamp Fog'] },
  { name: 'Salt Crusted',       mat: ['Mystic Energy'] },
  { name: 'Steaming Spell',     mat: ['Swamp Fog'] },
  { name: 'Steaming Nature',    mat: ['Swamp Fog'] },
  { name: 'Steaming Fervor',    mat: ['Heat From an Unearthly Pyre'] },
  { name: 'Oozing',             mat: ['Treant Blood'] },
  { name: 'Mineral Encrusted',  mat: ['Heat From an Unearthly Pyre'] },
  { name: 'Lightning Charged',  mat: ['Leviathan Blood'] },
  { name: 'Molten Magma',       mat: ['Leviathan Blood'] },
  { name: 'Light',              mat: ['Sun Light'] },
  { name: 'Blood',              mat: ['Giant Blood'] },
  { name: 'Mystical',           mat: ['Mystic Energy'] },
  { name: 'Mystic',             mat: ['Mystic Energy'] },
  { name: 'Brilliant',          mat: ['Draconic Fire', 'Mystic Energy', 'Treant Blood'] },
  { name: 'Finesse',            mat: ['Draconic Fire', 'Mystic Energy', 'Treant Blood'] },
  { name: 'Ethereal Spell',     mat: ['Swamp Fog'] },
  { name: 'Phantasmal Spell',   mat: ['Leviathan Blood'] },
  { name: 'Spectral Spell',     mat: ['Draconic Fire'] },
  { name: 'Ethereal Arcane',    mat: ['Leviathan Blood'] },
  { name: 'Phantasmal Arcane',  mat: ['Draconic Fire'] },
  { name: 'Spectral Arcane',    mat: ['Air Elemental Essence'] },
  { name: 'Aberrant',           mat: ['Treant Blood'] },
  { name: 'Embracing',          mat: ['Frost From a Wasteland'] },
  { name: 'Shadowy',            mat: ['Swamp Fog'] },
  { name: 'Blighted Primal',    mat: ['Air Elemental Essence'] },
  { name: 'Blighted Rune',      mat: ['Undead Ash and Holy Water'] },
  { name: 'Valiant',            mat: ['Swamp Fog'] },
  { name: 'Unholy',             mat: ['Air Elemental Essence'] },
  { name: 'Glacial',            mat: ['Frost From a Wasteland'] },
  { name: 'Cinder',             mat: ['Draconic Fire'] },
  { name: 'Radiant',            mat: ['Sun Light'] },
  { name: 'Magnetic',           mat: ['Mystic Energy'] },
  { name: 'Clout',              mat: ['Giant Blood'] }
];

LiquidsOrder = [
  'Air Elemental Essence',
  'Draconic Fire',
  'Frost From a Wasteland',
  'Giant Blood',
  'Heat From an Unearthly Pyre',
  'Leviathan Blood',
  'Mystic Energy',
  'Sun Light',
  'Swamp Fog',
  'Treant Blood',
  'Undead Ash and Holy Water'
];

DustMultiplier = {
  'Stat': [4, 1],
  'Resist': [5, 1],
  'Skill': [4, 1],
  'Focus': [5, 1],
  'All Magic Skills': [5, 1],
  'All Melee Skills': [5, 1]
};

LiquidMultiplier = {
  'Stat': [1, 1],
  'Resist': [1, 1],
  'Skill': [1, 1],
  'Focus': [1, 1],
  'All Magic Skills': [6, 2],
  'All Melee Skills': [6, 2]
};