Classes = {
  'Animist': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5, 'Staff': 12 },
  'Armsman': { 'Slash': 22, 'Crush': 22, 'Thrust': 22, 'Staff': 22, 'Two Handed': 22, 'Polearm': 22, 'Crossbow': 22 },
  'Bainshee': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5, 'Staff': 12 },
  'Bard': { 'Piercing': 5, 'Blades': 18, 'Blunt': 18, 'Staff': 18, 'Instruments': 19 },
  'Berserker': { 'Axe': 22, 'Sword': 22, 'Hammer': 22, 'Staff': 22, 'Thrown': 22 },
  'Blademaster': { 'Shortbow': 18, 'Staff': 20, 'Blades': 22, 'Blunt': 22, 'Piercing': 22 },
  'Bonedancer': { 'Axe': 5, 'Sword': 5, 'Hammer': 5, 'Staff': 14 },
  'Cabalist': { 'Slash': 5, 'Crush': 5, 'Thrust': 5, 'Staff': 12 },
  'Champion': { 'Blades': 19, 'Blunt': 19, 'Piercing': 19, 'Large Weapon': 19, 'Staff': 20 },
  'Cleric': { 'Slash': 5, 'Thrust': 5, 'Crush': 16, 'Staff': 16 },
  'Druid': { 'Piercing': 5, 'Blades': 16, 'Blunt': 16, 'Staff': 16 },
  'Eldritch': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5, 'Staff': 12 },
  'Enchanter': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5, 'Staff': 12 },
  'Friar': { 'Slash': 5, 'Thrust': 5, 'Crush': 18, 'Staff': 20 },
  'Healer': { 'Axe': 5, 'Sword': 18, 'Hammer': 18, 'Staff': 18 },
  'Heretic': { 'Slash': 5, 'Thrust': 5, 'Crush': 18, 'Staff': 18, 'Flexible': 20 },
  'Hero': { 'Shortbow': 18, 'Staff': 20, 'Blades': 22, 'Blunt': 22, 'Piercing': 22, 'Large Weapon': 22, 'Celtic Spear': 22 },
  'Hunter': { 'Hammer': 5, 'Staff': 18, 'Axe': 19, 'Sword': 19, 'Spear': 19 },
  'Infiltrator': { 'Crush': 5, 'Slash': 18, 'Thrust': 18, 'Staff': 18, 'Crossbow': 18 },
  'Mauler': { 'Fist Wraps': 20, 'Mauler Staff': 20 },
  'Mentalist': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5, 'Staff': 12 },
  'Mercenary': { 'Shortbow': 20, 'Slash': 22, 'Crush': 22, 'Thrust': 22, 'Staff': 22 },
  'Minstrel': { 'Crush': 5, 'Instruments': 17, 'Slash': 18, 'Thrust': 18, 'Staff': 18 },
  'Necromancer': { 'Slash': 5, 'Crush': 5, 'Thrust': 5, 'Staff': 12 },
  'Nightshade': { 'Blunt': 5, 'Blades': 18, 'Piercing': 18, 'Staff': 18 },
  'Paladin': { 'Slash': 19, 'Crush': 19, 'Thrust': 19, 'Two Handed': 19, 'Staff': 20 },
  'Ranger': { 'Blunt': 5, 'Blades': 18, 'Piercing': 18, 'Staff': 16 },
  'Reaver': { 'Slash': 19, 'Crush': 19, 'Thrust': 19, 'Flexible': 19, 'Staff': 20 },
  'Runemaster': { 'Axe': 5, 'Sword': 5, 'Hammer': 5, 'Staff': 14 },
  'Savage': { 'Staff': 22, 'Axe': 20, 'Sword': 20, 'Hammer': 20, 'Hand to Hand': 20 },
  'Scout': { 'Crush': 18, 'Staff': 18, 'Slash': 19, 'Thrust': 19 },
  'Shadowblade': { 'Hammer': 5, 'Staff': 16, 'Axe': 18, 'Sword': 18, 'Thrown': 18 },
  'Shaman': { 'Axe': 5, 'Sword': 18, 'Hammer': 18, 'Staff': 18 },
  'Skald': { 'Axe': 19, 'Sword': 19, 'Hammer': 19, 'Staff': 19 },
  'Sorcerer': { 'Slash': 5, 'Crush': 5, 'Thrust': 5, 'Staff': 12 },
  'Spiritmaster': { 'Axe': 5, 'Sword': 5, 'Hammer': 5, 'Staff': 12 },
  'Thane': { 'Axe': 18, 'Sword': 18, 'Hammer': 19, 'Staff': 20 },
  'Theurgist': { 'Slash': 5, 'Crush': 5, 'Thrust': 5, 'Staff': 14 },
  'Valewalker': { 'Axe': 5, 'Hammer': 5, 'Staff': 20, 'Scythe': 21 },
  'Valewalker': { 'Blades': 5, 'Blunt': 5, 'Piercing': 5 },
  'Valkyrie': { 'Sword': 18, 'Spear': 19, 'Staff': 20 },
  'Vampiir': { 'Blades': 5, 'Blunt': 5, 'Staff': 20, 'Piercing': 22 },
  'Warden': { 'Piercing': 5, 'Staff': 16, 'Blades': 18, 'Blunt': 18, 'Shortbow': 18 },
  'Warlock': { 'Axe': 5, 'Sword': 5, 'Hammer': 5, 'Staff': 12 },
  'Warrior': { 'Staff': 22, 'Thrown': 22, 'Axe': 23, 'Sword': 23, 'Hammer': 23 },
  'Wizard': { 'Slash': 5, 'Crush': 5, 'Thrust': 5, 'Staff': 12 }
};

WeaponStats = {
  'Axe': 0,
  'Blades': 0,
  'Blunt': 0,
  'Celtic Spear': 0,
  'Crossbow': 1,
  'Crush': 0,
  'Fist Wraps': 0,
  'Flexible': 2,
  'Hammer': 0,
  'Hand to Hand': 3,
  'Instruments': 1,
  'Large Weapon': 0,
  'Mauler Staff': 1,
  'Piercing': 2,
  'Polearm': 0,
  'Shortbow': 1,
  'Slash': 0,
  'Spear': 2,
  'Staff': 1,
  'Sword': 0,
  'Thrown': 0,
  'Thrust': 2,
  'Two Handed': 0
};